#pragma once

//Misc error codes
#pragma region MiscErrorCodes
#define ERROR_BASE												100
#define ERROR_UNKNOWN_ERROR_CODE								ERROR_BASE+1
#define ERROR_LOGGER_CANT_OPEN_FILE								ERROR_BASE + 2
#define ERROR_LOGGING_FILE_NOT_SET								ERROR_BASE + 3
#define ERROR_UNKNOWN_LOGGING_TYPE								ERROR_BASE + 4
#define ERROR_CANNOT_CONNECT_TO_DATABASE						ERROR_BASE + 5
#define ERROR_IN_QUERYING_DATABASE								ERROR_BASE + 6
#define ERROR_INVALID_RECEIVED_PACKET							ERROR_BASE + 7
#pragma endregion

//Server app error codes
#pragma region ServerErrorCodes
#define ERROR_SERVER_BASE										200
#define ERROR_SERVER_UNKNOWN_ERROR_CODE							ERROR_SERVER_BASE + 1
#define ERROR_SERVER_INSTANCE_IS_CREATED						ERROR_SERVER_BASE + 2
#define ERROR_SERVER_INSTANCE_DOESNT_EXIST						ERROR_SERVER_BASE + 3
#define ERROR_SERVER_USERNAME_NOT_AVAILABLE						ERROR_SERVER_BASE + 4
#define ERROR_SERVER_USER_NOT_FOUND								ERROR_SERVER_BASE + 5
#define ERROR_SERVER_IS_ALREADY_ON								ERROR_SERVER_BASE + 6
#define ERROR_SERVER_IS_ALREADY_OFF								ERROR_SERVER_BASE + 7
#define ERROR_SERVER_ALTERED_DATABASE_DATAS						ERROR_SERVER_BASE + 8
#define ERROR_SERVER_WINSOCK_STARTUP_FAILED						ERROR_SERVER_BASE + 9
#define ERROR_SERVER_WINSOCK_FAIL_TO_LISTEN						ERROR_SERVER_BASE + 10
#define ERROR_SERVER_WINSOCK_FAIL_TO_BIND						ERROR_SERVER_BASE + 11
#define ERROR_SERVER_PACKET_TYPE_UNRECOGNIZED					ERROR_SERVER_BASE + 12
#define ERROR_SERVER_NET_MANAGER_INSTANCE_IS_CREATED			ERROR_SERVER_BASE + 13
#define ERROR_SERVER_NET_MANAGER_INSTANCE_DOESNT_EXIST			ERROR_SERVER_BASE + 14
#define ERROR_SERVER_PACKET_VIRTUAL_METHOD_NOT_IMPLEMENTED		ERROR_SERVER_BASE + 15
#define ERROR_SERVER_INVALID_PACKET								ERROR_SERVER_BASE + 16
#define ERROR_SERVER_INVALID_USER_ACTION						ERROR_SERVER_BASE + 17
#define ERROR_SERVER_INVALID_MESSAGE_ACTION						ERROR_SERVER_BASE + 18
#define ERROR_SERVER_INVALID_PACKET_TYPE						ERROR_SERVER_BASE + 19

#pragma endregion

// Client app error codes
#pragma region ClientErrorCodes
#define ERROR_CLIENT_BASE										300
#define ERROR_CLIENT_UNKNOWN_ERROR_CODE							ERROR_CLIENT_BASE + 1
#define ERROR_CLIENT_INSTANCE_IS_CREATED						ERROR_CLIENT_BASE + 2
#define ERROR_CLIENT_INSTANCE_DOESNT_EXIST						ERROR_CLIENT_BASE + 3
#define ERROR_CLIENT_NO_USER_IS_LOGGED							ERROR_CLIENT_BASE + 4
#define ERROR_CLIENT_NO_ADMINISTRATOR_PRIVILEGES				ERROR_CLIENT_BASE + 5
#pragma endregion
